apiVersion: v1
kind: Pod
metadata:
  name: bash-pod5b
  annotations:
    description: "Test5b"
spec:
  containers:
  - name: bash-container3
    image: docker.io/bash:5.2
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: MY_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: configmap1
          key: MY_ENV_VAR
