apiVersion: v1
kind: Pod
metadata:
  name: bash-pod5
spec:
  containers:
  - name: bash-container4
    image: docker.io/bash:latest
    command: ["sleep"]
    args: ["infinity"]
    env:
    - name: MY_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: configmap1
          key: MY_ENV_VAR
